Initial Endurance QARTOD values for the METBK
oceanobservatories/qc-lookup pull request #39
Opened 2022-09-09 14:39 UTC by cwingard

Initial QARTOD gross range and climatology test limits for the METBK sensor. Excluded sea_surface_conductivity from the climatology tests in keeping with the spirit of the QARTOD manual for CTDs, though I did calculate the climatology and the tables are included. Commented out the barometric_pressure climatology as the variance explained values are very low. Left them as placeholders if we decide to include them. Will re-run the code to create the limits once review annotations are pushed and will update any sensor that is significantly different.

2022-09-09 15:03 UTC, crisien requested changes
The values all look OK to me except for the shortwave irr for CE02, CE04 and CE07 where there are positive lower bound values rather than zero. CE09 shortwave irr looks OK.

2022-09-28 20:40 UTC, reedan88 commented
Looks generally good to me. I have a question about the gross range sensor range you used for the wind speeds. The instrument specs say wind speed limit of 0 to 65 m/s. My reading of the method of operation for the WindObserver II is that the range we use should be (-65, 65) because it can measure up to 65 m/s in any one direction since ws = sqrt(u2 + v2). Or if want to use the max wind speed at 45 degree angles to N & E the range should probably be +/- 45 m/s.

2022-09-29 19:36 UTC, reedan88 approved these changes
Looks good except for the question on the sensor range for the eastward_wind_velocity and northward_wind_velocity.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE02SHSM,SBD11,06-METBKA000,metbk_a_dcl_instrument,{'inp': 'eastward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-9.92, 9.77], 'fail_span': [-32.5, 32.5]}}}",User range based o
Is the gross range sensor range here correct? The manual for the WindObserver II on the ASIMET say 0-65 m/s, which using minimum values for u and v would be 45 m/s for both vectors.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE02SHSM,SBD11,06-METBKA000,metbk_a_dcl_instrument,{'inp': 'northward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-10.4, 15.45], 'fail_span': [-32.5, 32.5]}}}",User range based
Same question on the sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE02SHSM,SBD11,06-METBKA000,metbk_a_dcl_instrument_recovered,{'inp': 'eastward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-9.92, 9.77], 'fail_span': [-32.5, 32.5]}}}",User ran
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE02SHSM,SBD11,06-METBKA000,metbk_a_dcl_instrument_recovered,{'inp': 'northward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-10.4, 15.45], 'fail_span': [-32.5, 32.5]}}}",User r
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE04OSSM,SBD11,06-METBKA000,metbk_a_dcl_instrument,{'inp': 'eastward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-8.62738, 10.58], 'fail_span': [-32.5, 32.5]}}}",User range bas
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE04OSSM,SBD11,06-METBKA000,metbk_a_dcl_instrument,{'inp': 'northward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-10.65, 15.615], 'fail_span': [-32.5, 32.5]}}}",User range bas
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE04OSSM,SBD11,06-METBKA000,metbk_a_dcl_instrument_recovered,{'inp': 'eastward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-8.62738, 10.58], 'fail_span': [-32.5, 32.5]}}}",User
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE04OSSM,SBD11,06-METBKA000,metbk_a_dcl_instrument_recovered,{'inp': 'northward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-10.65, 15.615], 'fail_span': [-32.5, 32.5]}}}",User
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE07SHSM,SBD11,06-METBKA000,metbk_a_dcl_instrument,{'inp': 'eastward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-11.66, 10.34], 'fail_span': [-32.5, 32.5]}}}",User range based
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE07SHSM,SBD11,06-METBKA000,metbk_a_dcl_instrument,{'inp': 'northward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-7.31, 12.6299], 'fail_span': [-32.5, 32.5]}}}",User range bas
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE07SHSM,SBD11,06-METBKA000,metbk_a_dcl_instrument_recovered,{'inp': 'eastward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-11.66, 10.34], 'fail_span': [-32.5, 32.5]}}}",User r
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE07SHSM,SBD11,06-METBKA000,metbk_a_dcl_instrument_recovered,{'inp': 'northward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-7.31, 12.6299], 'fail_span': [-32.5, 32.5]}}}",User
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE09OSSM,SBD11,06-METBKA000,metbk_a_dcl_instrument,{'inp': 'eastward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-11.93, 11.51853], 'fail_span': [-32.5, 32.5]}}}",User range ba
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE09OSSM,SBD11,06-METBKA000,metbk_a_dcl_instrument,{'inp': 'northward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-8.18426, 13.98], 'fail_span': [-32.5, 32.5]}}}",User range ba
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE09OSSM,SBD11,06-METBKA000,metbk_a_dcl_instrument_recovered,{'inp': 'eastward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-11.93, 11.51853], 'fail_span': [-32.5, 32.5]}}}",Use
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 commented on qartod/metbk/metbk_qartod_gross_range_test_values.csv
> +CE09OSSM,SBD11,06-METBKA000,metbk_a_dcl_instrument_recovered,{'inp': 'northward_wind_velocity'},"{'qartod': {'gross_range_test': {'suspect_span': [-8.18426, 13.98], 'fail_span': [-32.5, 32.5]}}}",Use
Same question on sensor range.

2022-09-29 19:36 UTC, reedan88 approved these changes

2022-10-06 15:49 UTC, bkuebel approved these changes

2022-12-05 22:56 UTC, closed without merging