MAB suspect ranges for CTDBP, CTDMO, CTDPF, DOSTA, and DOFST
oceanobservatories/qc-lookup pull request #80
Opened 2024-05-14 20:14 UTC by reedan88

2024-05-15 21:08 UTC, mvardaro commented on qartod/ctdpf/ctdpf_qartod_gross_range_test_values.csv
> +CP14NEPM,WFP01,03-CTDPFK000,ctdpf_ckl_wfp_instrument_recovered,{'inp': 'practical_salinity'},"{'qartod': {'gross_range_test': {'fail_span': [0, 42], 'suspect_span': [0, 406.9531]}}}","Sensor min/max
The upper "suspect_span" value here looks suspect (compared to the fail_span).

2024-05-15 21:09 UTC, mvardaro commented on qartod/ctdpf/ctdpf_qartod_gross_range_test_values.csv
> +CP14NEPM,WFP01,03-CTDPFK000,ctdpf_ckl_wfp_instrument,{'inp': 'practical_salinity'},"{'qartod': {'gross_range_test': {'fail_span': [0, 42], 'suspect_span': [0, 406.9531]}}}","Sensor min/max derived fr
The upper "suspect_span" value here looks suspect (compared to the fail_span).

2024-05-15 21:09 UTC, mvardaro commented on qartod/ctdpf/ctdpf_qartod_gross_range_test_values.csv
> +CP14SEPM,WFP01,03-CTDPFK000,ctdpf_ckl_wfp_instrument_recovered,{'inp': 'practical_salinity'},"{'qartod': {'gross_range_test': {'fail_span': [0, 42], 'suspect_span': [0, 406.9531]}}}","Sensor min/max
The upper "suspect_span" value here looks suspect (compared to the fail_span).

2024-05-15 21:18 UTC, mvardaro requested changes
Almost everything looks good, except for the NEPM and SEPM profiler CTDPF suspect_span values for salinity. The upper bounds look too high ('suspect_span': [0, 406.9531]) compared to the fail_span ('fail_span': [0, 42]).

2024-05-16 20:52 UTC, cwingard approved these changes
Really tight salinity range for those profilers. Does it really not vary that much there?

2024-05-17 15:33 UTC, reedan88 commented
@cwingard No, when I fixed the issue Mike pointed out, I accidentally created a _different_ issue. I fixed that up and now the ranges look much more like what I expect.

2024-05-17 15:36 UTC, merged